import Head from 'next/head';
import HomeApp from '@/components/App';

export default function Home() {
  return (
    <div>
      <Head>
        <title>with-jotai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeApp />
      </main>
    </div>
  );
}
